//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_INF_CORR
    {
        public int BANK_INF_ID { get; set; }
        public string SWIFT_ID { get; set; }
        public string CCY_CD { get; set; }
        public string MM_SETTL_BANK_ID { get; set; }
        public string MM_SETTL_BANK_ACTNO { get; set; }
        public string BRANCH_NO { get; set; }
        public string SETTL_BRANCH_NO { get; set; }
        public string ADD_BY { get; set; }
        public System.DateTime ADD_ON { get; set; }
        public string AUTHORIZE_BY { get; set; }
        public System.DateTime AUTHORIZE_ON { get; set; }
        public string STATUS { get; set; }
        public string DELETION_STATUS { get; set; }
        public string GIP_STATUS { get; set; }
        public string TRAN_NO { get; set; }
    
        public virtual BANK_INF BANK_INF { get; set; }
    }
}
