//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COVENANT_RECEIPT_TIMING
    {
        public byte TIMING_TYPE { get; set; }
        public string TIMING_DESC { get; set; }
        public byte INTERVAL { get; set; }
        public string DATE_PART { get; set; }
        public byte ORDER { get; set; }
    }
}
