//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COVENANT_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COVENANT_MASTER()
        {
            this.COVENANT_RECORD = new HashSet<COVENANT_RECORD>();
            this.LOAN_MASTER_COVENANT = new HashSet<LOAN_MASTER_COVENANT>();
        }
    
        public int COVENANT_NO { get; set; }
        public string CATEGORY { get; set; }
        public string BRANCH_NO { get; set; }
        public string CUST_ABBR { get; set; }
        public string ACCOUNT_OFFICER { get; set; }
        public string COV_TYPE { get; set; }
        public Nullable<byte> REPORT_TYPE { get; set; }
        public Nullable<byte> FREQ_TYPE { get; set; }
        public Nullable<byte> DAY_OF_MONTH_TYPE { get; set; }
        public Nullable<System.DateTime> COV_START_DATE { get; set; }
        public Nullable<System.DateTime> COV_END_DATE { get; set; }
        public Nullable<byte> TIME_OF_RECEIPT { get; set; }
        public Nullable<byte> CONDITION_TYPE { get; set; }
        public string MATH_SYMBOL { get; set; }
        public Nullable<decimal> VALUE { get; set; }
        public string DENOMINATION { get; set; }
        public Nullable<byte> MARGIN_BASE_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS { get; set; }
        public string PROC_BY { get; set; }
        public Nullable<System.DateTime> PROC_ON { get; set; }
        public string APPR_BY { get; set; }
        public Nullable<System.DateTime> APPR_ON { get; set; }
    
        public virtual COVENANT_CONDITION COVENANT_CONDITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COVENANT_RECORD> COVENANT_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN_MASTER_COVENANT> LOAN_MASTER_COVENANT { get; set; }
    }
}
