//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COVENANT_CONDITION_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COVENANT_CONDITION_GROUP()
        {
            this.COVENANT_CONDITION = new HashSet<COVENANT_CONDITION>();
        }
    
        public byte CONDITION_GROUP_TYPE { get; set; }
        public string CONDITION_GROUP_DESC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COVENANT_CONDITION> COVENANT_CONDITION { get; set; }
    }
}
