//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COVENANT_CONDITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COVENANT_CONDITION()
        {
            this.COVENANT_MASTER = new HashSet<COVENANT_MASTER>();
        }
    
        public byte CONDITION_TYPE { get; set; }
        public string CONDITION_DESC { get; set; }
        public Nullable<byte> CONDITION_GROUP { get; set; }
    
        public virtual COVENANT_CONDITION_GROUP COVENANT_CONDITION_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COVENANT_MASTER> COVENANT_MASTER { get; set; }
    }
}
