//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentSavingsStatement
    {
        public int Id { get; set; }
        public int StatementId { get; set; }
        public string Date { get; set; }
        public string ValueDate { get; set; }
        public string RefNo { get; set; }
        public string Debit { get; set; }
        public string Credit { get; set; }
        public string Balance { get; set; }
        public string Remarks { get; set; }
    
        public virtual Statement Statement { get; set; }
    }
}
