//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPT_PERMISSION
    {
        public int DEPT_ID { get; set; }
        public string DEPT_NAME { get; set; }
        public Nullable<bool> VIEW_USER { get; set; }
        public Nullable<bool> ACT_USER { get; set; }
        public Nullable<bool> VIEW_CUST { get; set; }
        public Nullable<bool> ACT_CUST { get; set; }
        public Nullable<bool> VIEW_FACILITY { get; set; }
        public Nullable<bool> ACT_FACILITY { get; set; }
        public Nullable<bool> VIEW_TRANS { get; set; }
        public Nullable<bool> ACT_TRANS { get; set; }
        public Nullable<bool> VIEW_COVENANT { get; set; }
        public Nullable<bool> ACT_COVENANT { get; set; }
        public Nullable<bool> VIEW_AO { get; set; }
        public Nullable<bool> ACT_AO { get; set; }
        public Nullable<bool> VIEW_LOAN { get; set; }
        public Nullable<bool> ACT_LOAN { get; set; }
    }
}
