//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomesticClearing_GOPosting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DomesticClearing_GOPosting()
        {
            this.DomesticClearing_Payment = new HashSet<DomesticClearing_Payment>();
            this.DomesticClearing_Payment1 = new HashSet<DomesticClearing_Payment>();
        }
    
        public int GOPostingId { get; set; }
        public string GBaseRefNo { get; set; }
        public string TransNo { get; set; }
        public System.DateTime ValueDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public string CurrencyCode { get; set; }
        public string Remark { get; set; }
        public string DebitAccountCode { get; set; }
        public string DebitAccountNo { get; set; }
        public string CreditAccountCode { get; set; }
        public string CreditAccountNo { get; set; }
        public string DebitCustomerAbbreviation { get; set; }
        public string CreditCustomerAbbreviation { get; set; }
        public int DirectionId { get; set; }
        public string CreditMinNo { get; set; }
        public string DebitMinNo { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int PostingTypeId { get; set; }
        public string StatusIdUpdatedWho { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public Nullable<int> PaymentLineId { get; set; }
        public string BranchNo { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> UpdatedWhen { get; set; }
        public string UpdatedWho { get; set; }
        public System.DateTime CreatedWhen { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public string ChequeNo { get; set; }
        public string GasDescription { get; set; }
        public Nullable<int> PreviousStatusId { get; set; }
    
        public virtual GAS_GO_DEBIT GAS_GO_DEBIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DomesticClearing_Payment> DomesticClearing_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DomesticClearing_Payment> DomesticClearing_Payment1 { get; set; }
    }
}
