//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomesticClearing_Payment
    {
        public int PaymentId { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public string CurrencyCode { get; set; }
        public string CustomerCurrentAccount { get; set; }
        public Nullable<System.DateTime> UpdatedWhen { get; set; }
        public string UpdatedWho { get; set; }
        public System.DateTime CreatedWhen { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string StatusIdUpdatedWho { get; set; }
        public string GCMSReferenceNumber { get; set; }
        public Nullable<int> DirectionId { get; set; }
        public Nullable<int> MainPostId { get; set; }
        public Nullable<int> FeePostId { get; set; }
        public string CustomerAbbreviation { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public string BranchNo { get; set; }
        public Nullable<bool> IsClearerExtracted { get; set; }
        public string ClearerExtractFileName { get; set; }
        public string UnitCode { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> Lines { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<bool> IsPaymentGOPosted { get; set; }
        public Nullable<bool> IsFeeGOPosted { get; set; }
        public Nullable<bool> IsClearerReceived { get; set; }
        public string BSB { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public string OriginalAccountName { get; set; }
        public Nullable<int> ChequesCount { get; set; }
        public Nullable<decimal> ChequesValue { get; set; }
        public Nullable<decimal> CashValue { get; set; }
        public string ChequeNo { get; set; }
        public string Remark { get; set; }
        public Nullable<int> PreviousStatusId { get; set; }
        public Nullable<System.DateTime> LowPriorityWhen { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<bool> IsDepartmentHandling { get; set; }
        public string DEReplyFilename { get; set; }
        public string ChequeFrontImageName { get; set; }
        public string ChequeReverseImageName { get; set; }
    
        public virtual DomesticClearing_GOPosting DomesticClearing_GOPosting { get; set; }
        public virtual DomesticClearing_GOPosting DomesticClearing_GOPosting1 { get; set; }
    }
}
