//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eDocumentDBEntities : DbContext
    {
        public eDocumentDBEntities()
            : base("name=eDocumentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CurrentSavingsStatement> CurrentSavingsStatements { get; set; }
        public virtual DbSet<ForeignExchangeConfirmation> ForeignExchangeConfirmations { get; set; }
        public virtual DbSet<ForeignExchangeStatement> ForeignExchangeStatements { get; set; }
        public virtual DbSet<gBaseDocument> gBaseDocuments { get; set; }
        public virtual DbSet<MoneyMarketConfirmation> MoneyMarketConfirmations { get; set; }
        public virtual DbSet<MoneyMarketStatement> MoneyMarketStatements { get; set; }
        public virtual DbSet<Statement> Statements { get; set; }
    }
}
