//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EUCDbArchiveDBEntities : DbContext
    {
        public EUCDbArchiveDBEntities()
            : base("name=EUCDbArchiveDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOAN_TRANCHE_CONTENT_BATCH> LOAN_TRANCHE_CONTENT_BATCH { get; set; }
        public virtual DbSet<LOAN_TRANCHE_MASTER_BATCH> LOAN_TRANCHE_MASTER_BATCH { get; set; }
        public virtual DbSet<OnDemand_Batch> OnDemand_Batch { get; set; }
        public virtual DbSet<OnDemand_Batch_Log> OnDemand_Batch_Log { get; set; }
        public virtual DbSet<OnDemand_Lock> OnDemand_Lock { get; set; }
    }
}
