//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACILITY_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACILITY_MASTER()
        {
            this.LOAN_TRANS = new HashSet<LOAN_TRANS>();
        }
    
        public string REF_NO { get; set; }
        public string APPLN_NO { get; set; }
        public string APPLN_NO1 { get; set; }
        public string RATING1 { get; set; }
        public Nullable<short> RATING2 { get; set; }
        public Nullable<short> PROD_TYPE1 { get; set; }
        public Nullable<short> PROD_TYPE2 { get; set; }
        public Nullable<short> PROD_TYPE3 { get; set; }
        public Nullable<short> PROD_TYPE4 { get; set; }
        public Nullable<System.DateTime> APPR_DATE { get; set; }
        public Nullable<System.DateTime> APPR_DATE1 { get; set; }
        public Nullable<bool> MULTI_CCY { get; set; }
        public string BASE_CCY { get; set; }
        public Nullable<decimal> LIMIT { get; set; }
        public Nullable<System.DateTime> MAT_DATE { get; set; }
        public Nullable<System.DateTime> SIGHT_DATE { get; set; }
        public string MAX_INT_PERIOD { get; set; }
        public string BASE_RATE { get; set; }
        public string BASE_RATE_REMARK { get; set; }
        public Nullable<decimal> MARGIN { get; set; }
        public Nullable<short> INT_CALC_METHOD { get; set; }
        public string INT_CALC_REMARK { get; set; }
        public Nullable<short> REPAY_TYPE { get; set; }
        public string REPAY_REMARK { get; set; }
        public string OTHER_REMARK { get; set; }
        public Nullable<short> G_FEE_TYPE { get; set; }
        public Nullable<decimal> G_FEE_RATE { get; set; }
        public byte FEE_KIND_ID { get; set; }
        public decimal FEE_RATE { get; set; }
        public byte FEE_CALC_METHOD_TYPE { get; set; }
        public System.DateTime FEE_START_DATE { get; set; }
        public System.DateTime FEE_END_DATE { get; set; }
        public byte FEE_PAYMENT_TYPE { get; set; }
        public byte FREQ_TYPE { get; set; }
        public byte DAY_OF_MONTH_TYPE { get; set; }
        public System.DateTime FEE_COL_DATE { get; set; }
        public string FEE_REMARKS { get; set; }
        public string STATUS { get; set; }
        public string PROC_BY1 { get; set; }
        public string PROC_BY2 { get; set; }
        public string APPR_BY1 { get; set; }
        public string APPR_BY2 { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> APPR_ON { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string CUST_ABBR { get; set; }
        public string BRANCH_NO { get; set; }
        public bool DIRECT_DEBIT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN_TRANS> LOAN_TRANS { get; set; }
    }
}
