//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForeignExchangeConfirmation
    {
        public int Id { get; set; }
        public int gBaseDocumentId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string ContractDate { get; set; }
        public string ReferenceNumber { get; set; }
        public string OurPurchaseAmount { get; set; }
        public string OurPurchaseRate { get; set; }
        public string OurSaleAmount { get; set; }
        public string OurSaleDeliveryDate { get; set; }
        public string OurDueDate { get; set; }
        public string PleasePayTo { get; set; }
        public string WeWillPayTo { get; set; }
        public string Broker { get; set; }
        public string Remarks { get; set; }
        public string OperationDate { get; set; }
        public string TransactionNumber { get; set; }
        public string Operator { get; set; }
    
        public virtual gBaseDocument gBaseDocument { get; set; }
    }
}
