//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForeignExchangeStatement
    {
        public int Id { get; set; }
        public int StatementId { get; set; }
        public string ReferenceNo { get; set; }
        public string Currency { get; set; }
        public string OurPrice { get; set; }
        public string OurSale { get; set; }
        public string DealDate { get; set; }
        public string ValueDate { get; set; }
        public string Rate { get; set; }
        public string EquivalentAmountCurrency { get; set; }
        public string EquivalentAmount { get; set; }
        public string Remarks { get; set; }
    
        public virtual Statement Statement { get; set; }
    }
}
