//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FX_TRANSACTION_EXT
    {
        public string REF_NO { get; set; }
        public Nullable<long> PackageId { get; set; }
        public long RootContractId { get; set; }
        public long BaseContractId { get; set; }
        public long ContractId { get; set; }
        public long TradeId { get; set; }
        public string Event { get; set; }
        public string PortfolioGroup { get; set; }
        public string PortfolioDesk { get; set; }
        public string PortfolioBook { get; set; }
        public Nullable<decimal> BrokerFeeAmount { get; set; }
        public string SourceSystem { get; set; }
        public string SourceId { get; set; }
        public string SourceCtpy { get; set; }
        public string DealingMethod { get; set; }
        public string AuthorisedDealer { get; set; }
        public string CONTRACT_CCY_ABBR_ORIG { get; set; }
        public string EQUIV_CCY_ABBR_ORIG { get; set; }
        public Nullable<bool> Printed { get; set; }
        public Nullable<System.DateTime> PrintDateTime { get; set; }
        public bool GIDUpload { get; set; }
    }
}
