//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FXFCcy
    {
        public int CCY_ID { get; set; }
        public string CCY { get; set; }
        public string CCYDESC { get; set; }
        public Nullable<short> DAYS { get; set; }
        public bool DIRECT { get; set; }
        public string DreamsDesc { get; set; }
        public int SPREADVALUE { get; set; }
        public Nullable<int> FXBLOTTERORDER { get; set; }
        public string CCY_CD { get; set; }
        public string AUDCrossCCYName { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Reuters_Rate_Type { get; set; }
        public string Murex_Rate_Quotation { get; set; }
    }
}
