//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FXFCust
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FXFCust()
        {
            this.MxCustCounterpartyTypes = new HashSet<MxCustCounterpartyType>();
        }
    
        public int CUST_ID { get; set; }
        public string CODE { get; set; }
        public string SHORTNAME { get; set; }
        public string Abbreviation { get; set; }
        public string IBOSNO { get; set; }
        public string BRANCH { get; set; }
        public Nullable<int> ParentEntity_ID { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Active { get; set; }
        public string STATUS { get; set; }
        public string DELETION_STATUS { get; set; }
        public string ADD_BY { get; set; }
        public System.DateTime ADD_ON { get; set; }
        public string MODIFY_BY { get; set; }
        public string DELETE_BY { get; set; }
        public System.DateTime DELETE_ON { get; set; }
        public System.DateTime MODIFY_ON { get; set; }
        public string AUTHORIZE_BY { get; set; }
        public System.DateTime AUTHORIZE_ON { get; set; }
        public string Call_Deposit_AUD_type { get; set; }
        public string Call_Deposit_FGN_type { get; set; }
        public string Call_Loan_AUD_type { get; set; }
        public string Call_Loan_FGN_type { get; set; }
        public string Description { get; set; }
        public string CCIF { get; set; }
        public string DeptCode { get; set; }
        public string TaxCode { get; set; }
        public string Category { get; set; }
        public string Sector { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string Street3 { get; set; }
        public string Street4 { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Telex { get; set; }
        public string Swift { get; set; }
        public string Email { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> MxGuideCustDetailId { get; set; }
    
        public virtual MxGuideCustDetail MxGuideCustDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MxCustCounterpartyType> MxCustCounterpartyTypes { get; set; }
    }
}
