//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FXFSwift
    {
        public int ID { get; set; }
        public int SIF_ID { get; set; }
        public string RECORD_KIND { get; set; }
        public string CUST_CODE { get; set; }
        public string CCY_CD { get; set; }
        public Nullable<int> CCY_ID { get; set; }
        public string Addresse { get; set; }
        public string PartyIdentifier56 { get; set; }
        public string BIC56_1 { get; set; }
        public string PartyIdentifier57 { get; set; }
        public string FXALM_PartyIdentifier57 { get; set; }
        public string BIC57_1 { get; set; }
        public string BIC57_2 { get; set; }
        public string BIC57_3 { get; set; }
        public string BIC57_4 { get; set; }
        public string PartyIdentifier58 { get; set; }
        public string FXALM_PartyIdentifier58 { get; set; }
        public string BIC58_1 { get; set; }
        public string PartyIdentifier59 { get; set; }
        public string BIC59_1 { get; set; }
        public string BIC59_2 { get; set; }
        public string BIC59_3 { get; set; }
        public string BIC59_4 { get; set; }
        public string SpecialInstruction_1 { get; set; }
        public string SpecialInstruction_2 { get; set; }
        public string SpecialInstruction_3 { get; set; }
        public string SpecialInstruction_4 { get; set; }
        public string STATUS { get; set; }
        public string DELETION_STATUS { get; set; }
        public string ADD_BY { get; set; }
        public Nullable<System.DateTime> ADD_ON { get; set; }
        public string AUTHORIZE_BY { get; set; }
        public Nullable<System.DateTime> AUTHORIZE_ON { get; set; }
    }
}
