//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class gBaseDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gBaseDocument()
        {
            this.ForeignExchangeConfirmations = new HashSet<ForeignExchangeConfirmation>();
            this.MoneyMarketConfirmations = new HashSet<MoneyMarketConfirmation>();
            this.Statements = new HashSet<Statement>();
        }
    
        public int Id { get; set; }
        public string ReportType { get; set; }
        public string ReportFileName { get; set; }
        public string ReportArchiveLocation { get; set; }
        public bool Processed { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public bool Errored { get; set; }
        public string ErrorMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForeignExchangeConfirmation> ForeignExchangeConfirmations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoneyMarketConfirmation> MoneyMarketConfirmations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statement> Statements { get; set; }
    }
}
