//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GUIDEDBEntities : DbContext
    {
        public GUIDEDBEntities()
            : base("name=GUIDEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SETTLEMENT_INF> SETTLEMENT_INF { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<BANK_INF> BANK_INF { get; set; }
        public virtual DbSet<BANK_INF_CORR> BANK_INF_CORR { get; set; }
        public virtual DbSet<CUSTOMER_MASTER> CUSTOMER_MASTER { get; set; }
        public virtual DbSet<FX_SETTLEMENT_INF> FX_SETTLEMENT_INF { get; set; }
        public virtual DbSet<FX_TRANSACTION> FX_TRANSACTION { get; set; }
        public virtual DbSet<FXFSwift> FXFSwifts { get; set; }
        public virtual DbSet<FXFCcy> FXFCcies { get; set; }
        public virtual DbSet<FXFCust> FXFCusts { get; set; }
        public virtual DbSet<MxCustomerEvent> MxCustomerEvents { get; set; }
        public virtual DbSet<MxInboundEvent> MxInboundEvents { get; set; }
        public virtual DbSet<MxInboundEventLog> MxInboundEventLogs { get; set; }
        public virtual DbSet<FX_TRANSACTION_EXT> FX_TRANSACTION_EXT { get; set; }
        public virtual DbSet<MxCustomerStatu> MxCustomerStatus { get; set; }
        public virtual DbSet<MxEucBalanceEvent> MxEucBalanceEvents { get; set; }
        public virtual DbSet<MxGuideCustDetail> MxGuideCustDetails { get; set; }
        public virtual DbSet<MxInboundMessageStatu> MxInboundMessageStatus { get; set; }
        public virtual DbSet<MxTaxCode> MxTaxCodes { get; set; }
        public virtual DbSet<USER_SECURITY_GROUPS> USER_SECURITY_GROUPS { get; set; }
        public virtual DbSet<USERS_Ext> USERS_Ext { get; set; }
        public virtual DbSet<SETTLEMENT_CORP_CUST_DEFAULT> SETTLEMENT_CORP_CUST_DEFAULT { get; set; }
        public virtual DbSet<AUDIT_LOG> AUDIT_LOG { get; set; }
        public virtual DbSet<SECURITY_GROUPS> SECURITY_GROUPS { get; set; }
        public virtual DbSet<MoneyMarketTicket> MoneyMarketTickets { get; set; }
        public virtual DbSet<PaymentControl_MatchMoneyMarket> PaymentControl_MatchMoneyMarket { get; set; }
        public virtual DbSet<PaymentControl_Payment> PaymentControl_Payment { get; set; }
        public virtual DbSet<PaymentControl_PaymentLog> PaymentControl_PaymentLog { get; set; }
        public virtual DbSet<PaymentControl_Status> PaymentControl_Status { get; set; }
        public virtual DbSet<PaymentControl_SwiftPayment> PaymentControl_SwiftPayment { get; set; }
        public virtual DbSet<PaymentControl_SwiftPaymentLog> PaymentControl_SwiftPaymentLog { get; set; }
        public virtual DbSet<PaymentControl_SwiftAck> PaymentControl_SwiftAck { get; set; }
        public virtual DbSet<PaymentControl_Product> PaymentControl_Product { get; set; }
        public virtual DbSet<PaymentControl_ProductReference> PaymentControl_ProductReference { get; set; }
        public virtual DbSet<MxCounterpartyType> MxCounterpartyTypes { get; set; }
        public virtual DbSet<MxCustCounterpartyType> MxCustCounterpartyTypes { get; set; }
        public virtual DbSet<OPD_37_Loan_Raw> OPD_37_Loan_Raw { get; set; }
        public virtual DbSet<OPD_37_Swap_Raw> OPD_37_Swap_Raw { get; set; }
        public virtual DbSet<GAS_GO_DEBIT> GAS_GO_DEBIT { get; set; }
        public virtual DbSet<DomesticClearing_GOPosting> DomesticClearing_GOPosting { get; set; }
        public virtual DbSet<DomesticClearing_Payment> DomesticClearing_Payment { get; set; }
    }
}
