//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCS_CUST_MASTER
    {
        public string CUST_ABBR { get; set; }
        public string BRANCH_NO { get; set; }
        public string CONTACT { get; set; }
        public string STATUS { get; set; }
        public string PREP_BY { get; set; }
        public Nullable<System.DateTime> PREP_ON { get; set; }
        public string APPR_BY { get; set; }
        public Nullable<System.DateTime> APPR_ON { get; set; }
    }
}
