//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAN_MASTER()
        {
            this.LOAN_MASTER_ACCOUNT_OFFICER = new HashSet<LOAN_MASTER_ACCOUNT_OFFICER>();
            this.LOAN_MASTER_BORROWER = new HashSet<LOAN_MASTER_BORROWER>();
            this.LOAN_MASTER_RATING = new HashSet<LOAN_MASTER_RATING>();
            this.LOAN_MASTER_SECURITY = new HashSet<LOAN_MASTER_SECURITY>();
            this.TRANCHE_MASTER = new HashSet<TRANCHE_MASTER>();
            this.LOAN_MASTER_COVENANT = new HashSet<LOAN_MASTER_COVENANT>();
        }
    
        public int LOAN_NO { get; set; }
        public string BRANCH_NO { get; set; }
        public string CUST_ABBR { get; set; }
        public Nullable<bool> MULTI_BRW { get; set; }
        public Nullable<System.DateTime> AGREEM_DATE1 { get; set; }
        public Nullable<System.DateTime> AGREEM_DATE2 { get; set; }
        public string AMENDMENT_DATE { get; set; }
        public string RATING { get; set; }
        public Nullable<short> PROD_TYPE2 { get; set; }
        public Nullable<short> PROD_TYPE4 { get; set; }
        public string REMARKS { get; set; }
        public string AGENT { get; set; }
        public string ADDRESS { get; set; }
        public string CONTACT { get; set; }
        public string TEL_NO { get; set; }
        public string FAX_NO { get; set; }
        public string STATUS { get; set; }
        public string PROC_BY { get; set; }
        public Nullable<System.DateTime> PROC_ON { get; set; }
        public string APPR_BY { get; set; }
        public Nullable<System.DateTime> APPR_ON { get; set; }
        public string CCIF { get; set; }
        public string CCIF_NAME { get; set; }
        public string GCIF { get; set; }
        public string RATIO_SPREAD1 { get; set; }
        public string RATIO_SPREAD2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN_MASTER_ACCOUNT_OFFICER> LOAN_MASTER_ACCOUNT_OFFICER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN_MASTER_BORROWER> LOAN_MASTER_BORROWER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN_MASTER_RATING> LOAN_MASTER_RATING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN_MASTER_SECURITY> LOAN_MASTER_SECURITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANCHE_MASTER> TRANCHE_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAN_MASTER_COVENANT> LOAN_MASTER_COVENANT { get; set; }
    }
}
