//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN_TRANS
    {
        public string REF_NO { get; set; }
        public int TRANS_NO { get; set; }
        public Nullable<int> RO_NO { get; set; }
        public string STATUS { get; set; }
        public System.DateTime START_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<bool> INC_DUE_DATE { get; set; }
        public Nullable<int> DAYS { get; set; }
        public string DRAW_CCY { get; set; }
        public Nullable<decimal> DRAW_AMT { get; set; }
        public Nullable<decimal> DRAW_EQUIV { get; set; }
        public string DRAW_EXCH_RATE_IND { get; set; }
        public Nullable<decimal> DRAW_EXCH_RATE { get; set; }
        public string REPAY_CCY { get; set; }
        public Nullable<decimal> REPAY_AMT { get; set; }
        public Nullable<decimal> REPAY_EQUIV { get; set; }
        public string REPAY_EXCH_RATE_IND { get; set; }
        public Nullable<decimal> REPAY_EXCH_RATE { get; set; }
        public Nullable<decimal> BAL_AMT { get; set; }
        public Nullable<decimal> INT_RATE { get; set; }
        public Nullable<decimal> BASE_RATE { get; set; }
        public Nullable<decimal> INT_AMT { get; set; }
        public Nullable<decimal> INT_AMT_CALC { get; set; }
        public string INT_RECV_DATE { get; set; }
        public string INT_RECV_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string PROC_BY1 { get; set; }
        public string PROC_BY2 { get; set; }
        public string APPR_BY1 { get; set; }
        public string APPR_BY2 { get; set; }
        public string CHK_BY { get; set; }
        public string FLAG_DEL_BY { get; set; }
        public string REMARKS { get; set; }
        public Nullable<bool> INC_START_DATE { get; set; }
        public string DRAWDOWN_NO { get; set; }
        public string SCHEME_NO { get; set; }
        public string AUTHORIZED { get; set; }
        public Nullable<System.DateTime> FINAL_DUE_DATE { get; set; }
        public Nullable<System.DateTime> INTEREST_TO_DATE { get; set; }
        public string INTEREST_CALC_CODE { get; set; }
        public string BASE_RATE_CODE { get; set; }
        public Nullable<decimal> SPREAD { get; set; }
        public string INTEREST_COLLECT { get; set; }
        public string INTERNAL_RATE { get; set; }
        public string RECEIVING_METHOD { get; set; }
        public string PAYING_METHOD { get; set; }
        public Nullable<int> ACCOUNT_CODE { get; set; }
        public string CUSTOMER_ACCOUNT_CODE_BORROWER { get; set; }
        public Nullable<int> CUSTOMER_ACCOUNT_CODE { get; set; }
        public Nullable<int> ACCOUNT_NO1 { get; set; }
        public Nullable<int> ACCOUNT_NO2 { get; set; }
        public string ACCOUNT_NO1_MANUAL_ENTRY { get; set; }
        public string ACCOUNT_NO2_MANUAL_ENTRY { get; set; }
        public string ATTENTION { get; set; }
        public string Old_RO_InterestCollect { get; set; }
        public Nullable<decimal> Old_RO_IntAmt { get; set; }
        public string RO_Type1 { get; set; }
        public string RO_Type2 { get; set; }
        public Nullable<System.DateTime> InitialInputDateTime { get; set; }
        public Nullable<System.DateTime> InitialApprovalDateTime { get; set; }
        public Nullable<System.DateTime> FinalApprovalDateTime { get; set; }
        public Nullable<System.DateTime> ModifyRateDateTime { get; set; }
        public Nullable<System.DateTime> ApproveModifiedRateDateTime { get; set; }
        public string ModifyRatesBy { get; set; }
        public string AppRatesBy { get; set; }
    
        public virtual FACILITY_MASTER FACILITY_MASTER { get; set; }
    }
}
