//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN_MASTER_STATUS_CODE
    {
        public string MODULE { get; set; }
        public string STATUS_CODE { get; set; }
        public string SHORT_DESC { get; set; }
        public string FULL_DESC { get; set; }
    }
}
