//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN_MASTER_SECURITY
    {
        public int ID { get; set; }
        public int LOAN_NO { get; set; }
        public bool GUARANTEE { get; set; }
        public bool GUARANTOR { get; set; }
        public string GUARANTOR_SECURITY_TYPE { get; set; }
        public bool COLLATERAL { get; set; }
        public string COLLATERAL_SECURITY_TYPE { get; set; }
        public string COLLATERAL_LEDGER { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string DETAILS { get; set; }
        public string REMARKS { get; set; }
        public string COMMENT { get; set; }
        public string STATUS { get; set; }
    
        public virtual LOAN_MASTER LOAN_MASTER { get; set; }
    }
}
