//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN_MASTER_COVENANT
    {
        public int ID { get; set; }
        public int LOAN_NO { get; set; }
        public int COVENANT_NO { get; set; }
    
        public virtual COVENANT_MASTER COVENANT_MASTER { get; set; }
        public virtual LOAN_MASTER LOAN_MASTER { get; set; }
    }
}
