//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyMarketStatement
    {
        public int Id { get; set; }
        public int StatementId { get; set; }
        public string Date { get; set; }
        public string DebitCredit { get; set; }
        public string Principal { get; set; }
        public string Days { get; set; }
        public string Rate { get; set; }
        public string DealNo { get; set; }
        public string Term { get; set; }
        public string Comments { get; set; }
        public string Broker { get; set; }
        public string Interest { get; set; }
    
        public virtual Statement Statement { get; set; }
    }
}
