//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyMarketConfirmation
    {
        public int Id { get; set; }
        public int gBaseDocumentId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string ContractDate { get; set; }
        public string ReferenceNumber { get; set; }
        public string ValueDate { get; set; }
        public string DueDate { get; set; }
        public string Rate { get; set; }
        public string OldRate { get; set; }
        public string PrincipalAmount { get; set; }
        public string IncreaseDecrease { get; set; }
        public string ClosingBalance { get; set; }
        public string MHCBPayTo { get; set; }
        public string CustomerPayTo { get; set; }
        public string Broker { get; set; }
        public string Remarks { get; set; }
        public string Days { get; set; }
        public string OperationDate { get; set; }
        public string TransactionNumber { get; set; }
        public string Operator { get; set; }
        public string MurexEvent { get; set; }
        public string MurexGenerator { get; set; }
    
        public virtual gBaseDocument gBaseDocument { get; set; }
    }
}
