//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxCustCounterpartyType
    {
        public int ID { get; set; }
        public int CustID { get; set; }
        public int CounterpartyTypeID { get; set; }
    
        public virtual FXFCust FXFCust { get; set; }
        public virtual MxCounterpartyType MxCounterpartyType { get; set; }
    }
}
