//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxGuideCustDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MxGuideCustDetail()
        {
            this.FXFCusts = new HashSet<FXFCust>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MxCustomerEvent { get; set; }
        public Nullable<int> MxCustomerStatus { get; set; }
        public string EventId { get; set; }
        public Nullable<System.DateTime> TimeSent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FXFCust> FXFCusts { get; set; }
        public virtual MxCustomerEvent MxCustomerEvent1 { get; set; }
        public virtual MxCustomerStatu MxCustomerStatu { get; set; }
    }
}
