//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxInboundEvent
    {
        public int MessageId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string MessageXml { get; set; }
        public string SendingSystem { get; set; }
        public string Category { get; set; }
        public string EventType { get; set; }
        public System.DateTime EventDate { get; set; }
        public int StatusId { get; set; }
        public string Details { get; set; }
    }
}
