//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MxInboundEventLog
    {
        public int LogId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string LogLevel { get; set; }
        public string Logger { get; set; }
        public string EventId { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string Exception { get; set; }
    }
}
