//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPD_37_Swap_Raw
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AS_OF_DATE { get; set; }
        public string REF_1 { get; set; }
        public string REF_2 { get; set; }
        public string ENTITY { get; set; }
        public string ABBREVIATION { get; set; }
        public string GENERATOR { get; set; }
        public string CONTRACT_START_DT { get; set; }
        public string TRADE_DT { get; set; }
        public string MATURITY_DATE { get; set; }
        public string CORP { get; set; }
        public string CORP_NAME { get; set; }
        public string PRD { get; set; }
        public string M_CNT_TYPO { get; set; }
        public string PFOLIO { get; set; }
        public string INT_ACCRUAL_BUY_REC { get; set; }
        public string INT_ACCRUAL_SELL_PAY { get; set; }
        public string EFFECTIVERATETODAY_BUY_REC { get; set; }
        public string EFFECTIVERATETODAY_SELL_PAY { get; set; }
        public string M_TRN_FMLY { get; set; }
        public string M_TRN_GRP { get; set; }
        public string M_TP_RTPR0 { get; set; }
        public string M_PLIRDACC12 { get; set; }
        public string M_PLIRDACC22 { get; set; }
        public string M_TP_RTVLC00 { get; set; }
        public string M_TP_RTVLC01 { get; set; }
        public string M_TP_RTVLC02 { get; set; }
        public string M_TP_RTVLC10 { get; set; }
        public string M_TP_RTVLC11 { get; set; }
        public string M_TP_RTVLC12 { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> Processed { get; set; }
    }
}
