//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPD_37_Loan_Raw
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime AS_OF_DATE { get; set; }
        public string REF_1 { get; set; }
        public Nullable<int> REF_2 { get; set; }
        public string ENTITY { get; set; }
        public string ABBREVIATION { get; set; }
        public string GENERATOR { get; set; }
        public Nullable<System.DateTime> CONTRACT_START_DT { get; set; }
        public Nullable<System.DateTime> TRADE_DT { get; set; }
        public Nullable<System.DateTime> MATURITY_DATE { get; set; }
        public Nullable<int> CORP { get; set; }
        public string CORP_NAME { get; set; }
        public string PRD { get; set; }
        public string M_CNT_TYPO { get; set; }
        public string PFOLIO { get; set; }
        public Nullable<double> INT_ACCRUAL_BUY_REC { get; set; }
        public Nullable<double> INT_ACCRUAL_SELL_PAY { get; set; }
        public Nullable<double> INT_ACCRUAL_PrevEOM_BUY_REC { get; set; }
        public Nullable<double> INT_ACCRUAL_PrevEOM_SELL_PAY { get; set; }
        public Nullable<double> INT_ACCRUAL_Loan_PrevEOM { get; set; }
        public Nullable<double> INT_ACCRUAL_LOAN { get; set; }
        public Nullable<double> EFFECTIVERATETODAY_BUY_REC { get; set; }
        public Nullable<double> EFFECTIVERATETODAY_SELL_PAY { get; set; }
        public Nullable<double> EffectiveRatePrevEOM_BUY_REC { get; set; }
        public Nullable<double> EffectiveRatePrevEOM_SELL_PAY { get; set; }
        public Nullable<double> EffectiveRateTodayLeg1 { get; set; }
        public Nullable<double> EffectiveRateTodayLeg2 { get; set; }
        public Nullable<double> EffectiveRatePrevEOMLeg1 { get; set; }
        public Nullable<double> EffectiveRatePrevEOMLeg2 { get; set; }
        public string M_TRN_FMLY { get; set; }
        public string M_TRN_GRP { get; set; }
        public Nullable<double> M_PLIRDACC12 { get; set; }
        public Nullable<double> M_PLIRDACC22 { get; set; }
        public Nullable<double> M_TP_RTVLC00 { get; set; }
        public Nullable<double> M_TP_RTVLC01 { get; set; }
        public Nullable<double> M_TP_RTVLC02 { get; set; }
        public Nullable<double> M_TP_RTVLC10 { get; set; }
        public Nullable<double> M_TP_RTVLC11 { get; set; }
        public Nullable<double> M_TP_RTVLC12 { get; set; }
        public Nullable<double> BUY_AMTORBALANCE { get; set; }
        public Nullable<double> BUY_AMTOREOMBALANCE { get; set; }
        public string M_TP_BUY { get; set; }
        public Nullable<double> SELL_AMTORBALANCE { get; set; }
        public Nullable<double> SELL_AMTOREOMBALANCE { get; set; }
        public Nullable<double> M_PL_LQTY2 { get; set; }
        public Nullable<double> M_PL_LEQQTY2 { get; set; }
        public Nullable<double> M_TP_RTCCP01 { get; set; }
        public Nullable<double> M_TP_RTCCP02 { get; set; }
        public Nullable<double> M_TP_RTCCP11 { get; set; }
        public Nullable<double> M_TP_RTCCP12 { get; set; }
        public string M_TP_RTPR0 { get; set; }
        public string M_TP_RTCUR0 { get; set; }
        public string M_TP_RTCUR1 { get; set; }
        public string BUY_CUR { get; set; }
        public string SELL_CUR { get; set; }
        public string InterestPeriodStartLeg1 { get; set; }
        public string InterestPeriodStartLeg2 { get; set; }
        public string InterestPeriodStartLeg1PrevEOM { get; set; }
        public string InterestPeriodStartLeg2PrevEOM { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> Processed { get; set; }
    }
}
