//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentControl_PaymentLog
    {
        public int PaymentLogId { get; set; }
        public int PaymentId { get; set; }
        public System.DateTime When { get; set; }
        public string Who { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> UpdatedWhen { get; set; }
        public string UpdatedWho { get; set; }
    
        public virtual PaymentControl_Payment PaymentControl_Payment { get; set; }
    }
}
