//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentControl_Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentControl_Payment()
        {
            this.PaymentControl_MatchMoneyMarket = new HashSet<PaymentControl_MatchMoneyMarket>();
            this.PaymentControl_PaymentLog = new HashSet<PaymentControl_PaymentLog>();
            this.PaymentControl_SwiftPayment = new HashSet<PaymentControl_SwiftPayment>();
            this.PaymentControl_SwiftAck = new HashSet<PaymentControl_SwiftAck>();
        }
    
        public int PaymentId { get; set; }
        public string GBaseRefNo { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string PaymentCurrencyCode { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<int> ProductReferenceId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string CustomerAbbreviation { get; set; }
        public bool WaitingPayment { get; set; }
        public bool WaitingSwiftPayment { get; set; }
        public bool WaitingConfirmation { get; set; }
        public bool WaitingAckNack { get; set; }
        public bool WasManual { get; set; }
        public Nullable<System.DateTime> UpdatedWhen { get; set; }
        public string UpdatedWho { get; set; }
        public string StatusIdUpdatedWho { get; set; }
        public Nullable<System.DateTime> CreatedWhen { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> PreviousStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentControl_MatchMoneyMarket> PaymentControl_MatchMoneyMarket { get; set; }
        public virtual PaymentControl_Status PaymentControl_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentControl_PaymentLog> PaymentControl_PaymentLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentControl_SwiftPayment> PaymentControl_SwiftPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentControl_SwiftAck> PaymentControl_SwiftAck { get; set; }
        public virtual PaymentControl_ProductReference PaymentControl_ProductReference { get; set; }
    }
}
