//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentControl_ProductReference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentControl_ProductReference()
        {
            this.PaymentControl_Payment = new HashSet<PaymentControl_Payment>();
            this.PaymentControl_SwiftPayment = new HashSet<PaymentControl_SwiftPayment>();
        }
    
        public int ProductReferenceId { get; set; }
        public int ProductId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool HasConfirmations { get; set; }
        public bool HasSwiftPayments { get; set; }
        public bool IsTaking { get; set; }
        public Nullable<System.DateTime> UpdatedWhen { get; set; }
        public string UpdatedWho { get; set; }
        public System.DateTime CreatedWhen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentControl_Payment> PaymentControl_Payment { get; set; }
        public virtual PaymentControl_Product PaymentControl_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentControl_SwiftPayment> PaymentControl_SwiftPayment { get; set; }
    }
}
