//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentControl_SwiftPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentControl_SwiftPayment()
        {
            this.PaymentControl_SwiftPaymentLog = new HashSet<PaymentControl_SwiftPaymentLog>();
            this.PaymentControl_SwiftAck = new HashSet<PaymentControl_SwiftAck>();
        }
    
        public int SwiftPaymentId { get; set; }
        public string Payment { get; set; }
        public bool IsRtgs { get; set; }
        public string MessageType { get; set; }
        public bool Processed { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string GBaseRefNo { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ProductReferenceId { get; set; }
        public string SenderBank { get; set; }
        public string ReceiverBank { get; set; }
        public string BeneficiaryAccount { get; set; }
        public string BeneficiaryCustomer { get; set; }
        public Nullable<System.DateTime> UpdatedWhen { get; set; }
        public string UpdatedWho { get; set; }
        public string StatusIdUpdatedWho { get; set; }
        public bool HasOther { get; set; }
        public System.DateTime CreatedWhen { get; set; }
    
        public virtual PaymentControl_Payment PaymentControl_Payment { get; set; }
        public virtual PaymentControl_Status PaymentControl_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentControl_SwiftPaymentLog> PaymentControl_SwiftPaymentLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentControl_SwiftAck> PaymentControl_SwiftAck { get; set; }
        public virtual PaymentControl_ProductReference PaymentControl_ProductReference { get; set; }
    }
}
