//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentControl_SwiftAck
    {
        public int SwiftAckId { get; set; }
        public string MessageNo { get; set; }
        public string HostMessageNo { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.TimeSpan> AuthorisedTime { get; set; }
        public string MessageType { get; set; }
        public string MX { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ReceiverBankCode1 { get; set; }
        public string ReceiverBankCode2 { get; set; }
        public string ReceiverSwiftAddress { get; set; }
        public string ReceiverBankName { get; set; }
        public string ReceiverBranchCity { get; set; }
        public string OurRefNo { get; set; }
        public string TheirRefNo { get; set; }
        public string Reference { get; set; }
        public string BeneficiaryCustomerBank { get; set; }
        public string SectionNo { get; set; }
        public string SectionName { get; set; }
        public string Group { get; set; }
        public string OutgoingStatus { get; set; }
        public Nullable<System.DateTime> UpdatedWhen { get; set; }
        public string UpdatedWho { get; set; }
        public System.DateTime CreatedWhen { get; set; }
        public Nullable<int> SwiftPaymentId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public bool Processed { get; set; }
    
        public virtual PaymentControl_Payment PaymentControl_Payment { get; set; }
        public virtual PaymentControl_SwiftPayment PaymentControl_SwiftPayment { get; set; }
    }
}
