//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITY_GROUPS
    {
        public decimal IDENTIFIER { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string ENABLED_IND { get; set; }
        public System.DateTime CREATED_AMENDED_DATE { get; set; }
    }
}
