//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTLEMENT_CORP_CUST_DEFAULT
    {
        public int CORP_CUST_ID { get; set; }
        public string BRANCH_NO { get; set; }
        public string RECORD_KIND { get; set; }
        public string CCY_ABBR { get; set; }
        public string REC_SETTL_CODE { get; set; }
        public string REC_ACT_CD { get; set; }
        public string REC_ACT_NO { get; set; }
        public string REC_RMT_FLG { get; set; }
        public string REC_METHOD { get; set; }
        public string REC_MESSAGE_TYPE { get; set; }
        public string PAY_SETTL_CODE { get; set; }
        public string PAY_ACT_CD { get; set; }
        public string PAY_ACT_NO { get; set; }
        public string PAY_RMT_FLG { get; set; }
        public string PAY_METHOD { get; set; }
        public string PAY_MESSAGE_TYPE { get; set; }
        public string ADVICE_REC_FLG { get; set; }
        public decimal ADVICE_REC_LIMIT { get; set; }
        public string PRIORTY_FLG { get; set; }
        public string REC_BANK_ID { get; set; }
        public string INTERMEDIARY_BANK_ID { get; set; }
        public string ORDERING_CUSTOMER { get; set; }
        public string ORDERING_BANK { get; set; }
        public string BENE_BANK_ID { get; set; }
        public string ACC_BANK_ID { get; set; }
        public string SENDER_CORRES { get; set; }
        public string REC_CORRES { get; set; }
        public string STATUS { get; set; }
        public bool DEFAULT_FLG { get; set; }
    }
}
