//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTLEMENT_INF
    {
        public int SIF_ID { get; set; }
        public string BRANCH_NO { get; set; }
        public string RECORD_KIND { get; set; }
        public string CUST_ABBR { get; set; }
        public string CCY_CD { get; set; }
        public string REC_SETTL_CODE { get; set; }
        public string REC_ACT_CD { get; set; }
        public string REC_ACT_NO { get; set; }
        public string REC_RMT_FLG { get; set; }
        public string REC_METHOD { get; set; }
        public string REC_MESSAGE_TYPE { get; set; }
        public string PAY_SETTL_CODE { get; set; }
        public string PAY_ACT_CD { get; set; }
        public string PAY_ACT_NO { get; set; }
        public string PAY_RMT_FLG { get; set; }
        public string PAY_METHOD { get; set; }
        public string PAY_MESSAGE_TYPE { get; set; }
        public string PRIORTY_FLG { get; set; }
        public string BANK_FLG { get; set; }
        public string COVER_PO_FLG { get; set; }
        public string ADVICE_REC_FLG { get; set; }
        public Nullable<decimal> ADVICE_REC_LIMIT { get; set; }
        public string REC_BANK_ID { get; set; }
        public string REC_CUST_ABBR { get; set; }
        public string INTERMEDIARY_BANK_ID { get; set; }
        public string ACC_BANK_ID { get; set; }
        public string ACC_BANK_ACTNO { get; set; }
        public string BENE_BANK_ID { get; set; }
        public string BENE_BANK_ACTNO { get; set; }
        public string CONFIRMATION_SWIFT_ID { get; set; }
        public string CONFIRMATION_FLG { get; set; }
        public string REC_BANK_BR_ACTNO { get; set; }
        public string REC_BANK_HO_ACTNO { get; set; }
        public string BANK_INF_FLG { get; set; }
        public string BANK_INF { get; set; }
        public string OCNNECT_FLG { get; set; }
        public Nullable<System.DateTime> OPE_DATE { get; set; }
        public string REMARKS { get; set; }
        public string STATUS_CD { get; set; }
        public string ADD_BY { get; set; }
        public System.DateTime ADD_ON { get; set; }
        public string AUTHORIZE_BY { get; set; }
        public System.DateTime AUTHORIZE_ON { get; set; }
        public string MODIFY_BY { get; set; }
        public System.DateTime MODIFY_ON { get; set; }
        public string DELETE_BY { get; set; }
        public System.DateTime DELETE_ON { get; set; }
        public string STATUS { get; set; }
        public string DELETION_STATUS { get; set; }
        public string GIP_STATUS { get; set; }
        public string GIP_DESCRIPTION { get; set; }
        public string TRAN_NO { get; set; }
    }
}
