//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Statement()
        {
            this.CurrentSavingsStatements = new HashSet<CurrentSavingsStatement>();
            this.ForeignExchangeStatements = new HashSet<ForeignExchangeStatement>();
            this.MoneyMarketStatements = new HashSet<MoneyMarketStatement>();
        }
    
        public int Id { get; set; }
        public int gBaseDocumentId { get; set; }
        public string AccountType { get; set; }
        public string AccountNo { get; set; }
        public string Currency { get; set; }
        public string Period { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentSavingsStatement> CurrentSavingsStatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForeignExchangeStatement> ForeignExchangeStatements { get; set; }
        public virtual gBaseDocument gBaseDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoneyMarketStatement> MoneyMarketStatements { get; set; }
    }
}
