//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANCHE_MARGIN
    {
        public int ID { get; set; }
        public int TRANCHE_NO { get; set; }
        public string REF_NO { get; set; }
        public string RATIO_TYPE { get; set; }
        public string RATIO_RANGE { get; set; }
        public Nullable<decimal> RATIO_MARGIN { get; set; }
        public Nullable<decimal> LINE_FEE { get; set; }
        public Nullable<decimal> COMMITMENT_FEE { get; set; }
        public Nullable<decimal> PERFOMANCE_GNTEE { get; set; }
        public Nullable<decimal> FINANCIAL_GNTEE { get; set; }
        public Nullable<decimal> OTHER { get; set; }
        public bool SELECTED { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
    
        public virtual TRANCHE_MASTER TRANCHE_MASTER { get; set; }
    }
}
