//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANCHE_GUARANTEE
    {
        public int ID { get; set; }
        public int TRANCHE_NO { get; set; }
        public string GUARANTEE_NO { get; set; }
        public string GBASE_GUARANTEE_NO { get; set; }
        public string BORROWER { get; set; }
        public string MULTI_BORROWERS { get; set; }
        public string BENEFICIARY { get; set; }
        public string CCY { get; set; }
        public Nullable<decimal> ORIGINAL_AMOUNT { get; set; }
        public Nullable<decimal> OUTSTANDING_AMOUNT { get; set; }
        public Nullable<System.DateTime> BG_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> BG_CANCEL_DATE { get; set; }
        public Nullable<System.DateTime> BG_EXPIRY_DATE { get; set; }
        public string BG_REMARK { get; set; }
        public string STATUS { get; set; }
    
        public virtual TRANCHE_MASTER TRANCHE_MASTER { get; set; }
    }
}
