//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANCHE_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANCHE_MASTER()
        {
            this.TRANCHE_CONTENT = new HashSet<TRANCHE_CONTENT>();
            this.TRANCHE_GUARANTEE = new HashSet<TRANCHE_GUARANTEE>();
            this.TRANCHE_MARGIN = new HashSet<TRANCHE_MARGIN>();
        }
    
        public int TRANCHE_NO { get; set; }
        public Nullable<int> LOAN_NO { get; set; }
        public string TRANCHE_TYPE { get; set; }
        public string TRANCHE_NAME { get; set; }
        public Nullable<short> PROD_TYPE1 { get; set; }
        public Nullable<short> PROD_TYPE5 { get; set; }
        public string APPLN_NO { get; set; }
        public Nullable<System.DateTime> APPLN_DATE { get; set; }
        public Nullable<System.DateTime> HO_APPR_DATE { get; set; }
        public string APPLN_NO_RELT { get; set; }
        public Nullable<System.DateTime> APPLN_DATE_RELT { get; set; }
        public string BASE_CCY { get; set; }
        public Nullable<bool> MULTI_CCY { get; set; }
        public Nullable<decimal> TRANCHE_PORTION { get; set; }
        public Nullable<decimal> SYND_PORTION { get; set; }
        public string PORTION_NOTES { get; set; }
        public Nullable<System.DateTime> AVAIL_START { get; set; }
        public Nullable<System.DateTime> AVAIL_END { get; set; }
        public string PERIOD_NOTES { get; set; }
        public Nullable<System.DateTime> MAT_DATE { get; set; }
        public string MAT_DATE_NOTES { get; set; }
        public string MIN_DD { get; set; }
        public string MULTIPLE { get; set; }
        public string STATUS { get; set; }
        public string PROC_BY { get; set; }
        public Nullable<System.DateTime> PROC_ON { get; set; }
        public string APPR_BY { get; set; }
        public Nullable<System.DateTime> APPR_ON { get; set; }
        public string MULTI_CCY_DESC { get; set; }
        public short MAXI_DRAWDOWN_PERIOD { get; set; }
        public short MAXI_DRAWDOWN_DAYS { get; set; }
        public short MAXI_DRAWDOWN_TIMES { get; set; }
        public bool SILENT_MARGIN { get; set; }
        public string TRD_INTERNAL_RATE { get; set; }
        public string CFD_BASE_RATE { get; set; }
        public string MARGIN_11AM { get; set; }
        public string MARGIN_REMARK_11AM { get; set; }
        public bool RATING_TYPE { get; set; }
        public bool RATIIO_TYPE { get; set; }
        public string FINANCIAL_NAME { get; set; }
    
        public virtual LOAN_MASTER LOAN_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANCHE_CONTENT> TRANCHE_CONTENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANCHE_GUARANTEE> TRANCHE_GUARANTEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANCHE_MARGIN> TRANCHE_MARGIN { get; set; }
        public virtual TRANCHE_TYPE TRANCHE_TYPE1 { get; set; }
    }
}
