//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string USER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMPLOYEE_NO { get; set; }
        public Nullable<decimal> SG_IDENTIFIER { get; set; }
        public string ROLE { get; set; }
        public string ENABLED_IND { get; set; }
        public System.DateTime PWD_CREATE_DATE { get; set; }
        public string PWD_CHANGE_IND { get; set; }
        public System.DateTime CREATED_AMENDED_DATE { get; set; }
        public string DEPT_CODE { get; set; }
        public string REC_STATUS { get; set; }
        public string OPERATOR_ID { get; set; }
        public string RANK_CODE { get; set; }
        public string BU_STATUS_CODE { get; set; }
        public string ACU_STATUS_CODE { get; set; }
        public string SUB_DEPT_CODE { get; set; }
        public string CREATED_AMENDED_BY { get; set; }
        public Nullable<System.DateTime> GBASE_UPLOADED_DATE { get; set; }
        public string GBASE_STATUS_CODE { get; set; }
        public string RACF_STATUS_CODE { get; set; }
        public string RACF_PREVIOUS_PWD { get; set; }
        public Nullable<int> NO_OF_LOGIN_ATTEMPTS { get; set; }
        public string GBASE_PREVIOUS_PWD { get; set; }
        public string GBASE_PWD_BU_STATUS_CODE { get; set; }
        public string GBASE_PWD_ACU_STATUS_CODE { get; set; }
        public string GBASE_PWD_STATUS_CODE { get; set; }
        public string MASTER_ID { get; set; }
        public string APPROVED_BY { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string USER_PROFILE_STATUS { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public Nullable<System.DateTime> GBASE_REG_DATE { get; set; }
        public Nullable<System.DateTime> GBASE_MODI_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string PROFILE_EDITED_BY { get; set; }
        public Nullable<System.DateTime> PROFILE_EDITED_DATE { get; set; }
        public string RESET_BY { get; set; }
        public Nullable<System.DateTime> RESET_DATE { get; set; }
    
        public virtual USERS_Ext USERS_Ext { get; set; }
    }
}
