//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhcb.syd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGUIDE_CUSTOMER_MASTER
    {
        public string BRANCH_NO { get; set; }
        public string CUST_ABBR { get; set; }
        public string CUST_NAME { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string TEL_NO { get; set; }
        public string FAX_NO { get; set; }
        public string NATIONALITY { get; set; }
        public string STATUS_CD { get; set; }
        public string DEPARTMENT_CD { get; set; }
        public string STEPS_CUST_CD { get; set; }
        public string JAPANESE_FLG { get; set; }
        public string GUIDE_STATUS { get; set; }
        public string CCIF { get; set; }
        public string CCIF_NAME { get; set; }
    }
}
